//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVB5UL_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adatok
    {
        public int Csomag_ID { get; set; }
        public int Futar_ID { get; set; }
        public int Ugyfel_ID { get; set; }
        public string UgyfelNev { get; set; }
        public string Utca { get; set; }
        public int Hazszam { get; set; }
        public Nullable<int> Emelet { get; set; }
        public Nullable<int> Csengo { get; set; }
        public Nullable<int> Osszeg { get; set; }
        public string FizMod { get; set; }
        public bool Fizetve { get; set; }
    }
}
